spring:
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false